name: Build site and archive
on:
  - workflow_dispatch
  - push
jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Setup Dependencies
        run: uv sync

      - name: Build site
        run: uv run mkdocs build

      - name: Zip files
        run: zip -r release.zip site

      - name: Archive Exports
        uses: actions/upload-artifact@v4
        with:
          path: release.zip
          retention-days: 7
